version: '3.3'

services:

# -- Infrastructure
  mongo:
    build:
      context: infra/mongo
      dockerfile: Dockerfile
    ports:
      - "7011:27017"
    env_file:
      - etc/dev.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASS
      MONGO_INITDB_USERNAME: $MONGO_USER
      MONGO_INITDB_PASSWORD: $MONGO_PASS
      MONGO_INITDB_DATABASE: $MONGO_DB
    volumes:
      - ./infra/data/mongodb:/data/db
      - ./infra/mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./infra/mongo/mongo.conf:/etc/mongo.conf

  mongo-express:
    image: mongo-express:0.54
    ports:
      - "7012:8081"
    env_file:
      - etc/dev.env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_ROOT_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_ROOT_PASS
      ME_CONFIG_BASICAUTH_USERNAME: ''
      ME_CONFIG_BASICAUTH_PASSWORD: ''
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_PORT: $MONGO_PORT
      ME_CONFIG_MONGODB_SERVER: $MONGO_HOST
      ME_CONFIG_OPTIONS_EDITORTHEME: 'default'
      ME_CONFIG_REQUEST_SIZE: '100kb'
      ME_CONFIG_SITE_BASEURL: '/'
